on:
  push:
    branches:
      - develop

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v2
      - name: install node
        uses: actions/setup-node@v2
      - name: install dependencies
        run: npm install
      - name: build app
        run: npm run build
        env:
          NODE_ENV: "development"
          PUBLIC_URL: "https://glencoden.github.io/looney-website/"
      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: preview
          FOLDER: build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}"